
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

dotenv: .env
wallets:
  from_key: 0x024856bf34ffd2b857ba222e10c7649394c3caab0d928c6d69f245c8e5505df7
networks:
  kovan:
    price_feed_address: 9326bfa02add2366b30bacb125260af641031331
    verify: True
  mainnet-fork:
    price_feed_address: 5f4ec3df9cbd43714fe2740f5e3616155c5b8419
    verify: False
  mainnet-fork-dev:
    price_feed_address: 5f4ec3df9cbd43714fe2740f5e3616155c5b8419
    verify: False
  mainnet:
    price_feed_address: 5f4ec3df9cbd43714fe2740f5e3616155c5b8419
    verify: False
  deployment:
    verify: False
  ganache-local:
    verify: False
